### ISSUE TITLE
scrollbar is always shown for each item in the menu tree

### ISSUE THREAD

**Issue by kuchaguangjie** [cnshsliu/yarknodemenu#1]
On my browser, for the official demo https://menu-demo-lyart.vercel.app/

![a](https://user-images.githubusercontent.com/4230959/217691996-4ace6870-445e-44b6-8196-f481cb67d8c9.jpg)
![b](https://user-images.githubusercontent.com/4230959/217692016-831e85b5-5be3-475f-b649-9661641edaad.jpg)

**Comment by cnshsliu** [comment]
Please show more details about your environment, browser, os etc.

**Comment by kuchaguangjie** [comment]
browser: `Version 109.0.5414.119 (Official Build) (64-bit)`
os: `mint mate 20`
kernel: `Linux 5.4.0-26-generic #30-Ubuntu`

**Comment by cnshsliu** [comment]
I have no plan to support Linux desktop browser at this moment because I don't have Linux environment for testing.  If you like, maybe give it a try on Windows or Mac  systems which are normally  the environment for most of the end-users.

**Comment by kuchaguangjie** [comment]
Chrome browser should be the same across os, maybe it's some css issue.

**Comment by cnshsliu** [comment]
Of course, the problem you presented is also some easy to debug by yourself, open Your browser's devtool and see what happens there

**Comment by cnshsliu** [comment]
> Chrome browser should be the same across os, maybe it's some css issue.
Give it another try pls. I removed a css entry which may cause scrollbar visible on Linux.  

visit
https://menu-demo-lyart.vercel.app/

If those scollbars you saw disappear, then we fixed it.

Let me know the result on your side, thanks a lot.

**Comment by kuchaguangjie** [comment]
Yes, it's fixed I think, nice job !

![b](https://user-images.githubusercontent.com/4230959/218251462-2c120080-c67c-4478-8956-c90c63bddac0.jpg)
